- name: Audio Alerts
  platform: group
  services: 
    - service: google_say

- name: Text Alerts 
  platform: group
  services:
    - service: slack
    - service: mqtt_notify



- name: Pushbullet Channel
  platform: group
  services:
    - service: pushbullet
      data: 
        target:
          - !secret pushbullet_channel


- platform: rest
  name: mqtt_notify
  resource: 'http://192.168.120.34:8123/api/services/mqtt/publish'
  method: POST_JSON
  message_param_name: payload
  data:
    topic: flipdot/message
    retain: false
  headers:
      content-type: 'application/json'
      Authorization: !secret ha_bearer

- name: doorbell
  platform: rest
  resource: http://192.168.120.34:5000/play/doorbell.mp3

- name: laugh
  platform: rest
  resource: http://192.168.120.34:5000/play/evil_laugh.mp3

- name: door_chime
  platform: rest
  resource: http://192.168.120.34:5000/play/store_door.mp4

- name: google_say
  platform: rest
  resource: http://192.168.120.34:5000/say/
  message_param_name: text

- name: twilio
  platform: twilio_sms
  from_number: !secret twilio_number
- name: pushbullet
  platform: pushbullet
  api_key: !secret pushbullet_key

- name: slack
  platform: slack
  username: officebot
  api_key: !secret slack_key
  default_channel: '#office'
