- platform: template
  sensors:
    average_luminance:
      friendly_name: "Average Lumination"
      unit_of_measurement: "lx"
      value_template: >-
        {{( ((float(states("sensor.back_luminance")) + float(states("sensor.front_luminance")) ))  /2)|round(2)}}

