- platform: template
  sensors:
    average_temperature:
      friendly_name: "Average Temperature in Office"
      unit_of_measurement: "°F"
      value_template: >-
        {{ ((float(states(sensor.sensor.awair_temperature)) + float(states(sensor.front_temperature)) + float(states(sensor.back_temperature))) / 3) | round(2) }}

