- platform: template
  sensors:
    average_temperature:
      friendly_name: "Average Temperature in Office"
      unit_of_measurement: "째F"
      value_template: >-
        {{( ((float(states("sensor.awair_temperature")) + float(states("sensor.front_temperature")) + float(states("sensor.back_temperature"))) ) /3)|round(2)}}
    temperature_difference:
      friendly_name: "Temperature difference "
      unit_of_measurement: "째F"
      value_template: >-
        '{{ ( (states.sensor.average_temperature.state | float - 0.5 ) - ( states.weather.dark_sky.attributes.temperature | float ) ) | round(2) }}'
    front_temperature:
      friendly_name: "Front Temperature"
      unit_of_measurement: "째F"
      value_template: >-
        {{ ((float(states('sensor.front_front_motion_temperature')) * 9 / 5 )  +  32) | round(1) }}
    back_temperature:
      friendly_name: "Back Temperature"
      unit_of_measurement: "째F"
      value_template: >-
        {{ ((float(states('sensor.back_back_motion_temperature')) * 9 / 5 )  +  32) | round(1) }}


