
- alias: 'Office no longer occupied'
  trigger:
    platform: state
    entity_id: group.people
    from: 'home'
    to: 'not_home'
  action:
    - service: notify.text_alerts
      data:
        message: Everyone has left
    - service: input_boolean.turn_off
      entity_id: input_boolean.occupied

- alias: 'Office occupied'
  trigger:
    platform: state
    entity_id: group.people
    from: 'not_home'
    to: 'home'
  action:
    - service: notify.audio_alerts
      data:
        message: Hello
    - service: notify.text_alerts
      data:
        message: People have arrived
    - service: input_boolean.turn_on
      entity_id: input_boolean.occupied
